
package com.hub.chinatelecom;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DEPService", targetNamespace = "http://www.chinatelecom.hub.com", wsdlLocation = "http://136.64.44.237:9081/PrvncCrmExtrnlService/services/pCrmService?wsdl")
public class DEPService
    extends Service
{

    private final static URL DEPSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.hub.chinatelecom.DEPService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.hub.chinatelecom.DEPService.class.getResource(".");
            url = new URL(baseUrl, "http://136.64.44.237:9081/PrvncCrmExtrnlService/services/pCrmService?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://136.64.44.237:9081/PrvncCrmExtrnlService/services/pCrmService?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DEPSERVICE_WSDL_LOCATION = url;
    }

    public DEPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DEPService() {
        super(DEPSERVICE_WSDL_LOCATION, new QName("http://www.chinatelecom.hub.com", "DEPService"));
    }

    /**
     * 
     * @return
     *     returns DEPServicePortType
     */
    @WebEndpoint(name = "DEPServiceHttpPort")
    public DEPServicePortType getDEPServiceHttpPort() {
        return super.getPort(new QName("http://www.chinatelecom.hub.com", "DEPServiceHttpPort"), DEPServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DEPServicePortType
     */
    @WebEndpoint(name = "DEPServiceHttpPort")
    public DEPServicePortType getDEPServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.chinatelecom.hub.com", "DEPServiceHttpPort"), DEPServicePortType.class, features);
    }

}
