
package com.hub.chinatelecom;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DEPServicePortType", targetNamespace = "http://www.chinatelecom.hub.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DEPServicePortType {


    /**
     * 
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "out", targetNamespace = "http://www.chinatelecom.hub.com")
    @RequestWrapper(localName = "exchange", targetNamespace = "http://www.chinatelecom.hub.com", className = "com.hub.chinatelecom.Exchange")
    @ResponseWrapper(localName = "exchangeResponse", targetNamespace = "http://www.chinatelecom.hub.com", className = "com.hub.chinatelecom.ExchangeResponse")
    public String exchange(
        @WebParam(name = "in0", targetNamespace = "http://www.chinatelecom.hub.com")
        String in0);

}
